name: Copy Public Docker Image

on:
  workflow_dispatch:

jobs:
  copy-image:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull public image
      run: docker pull nginx:latest

    - name: Retag image
      run: docker tag nginx:latest ${{ secrets.DOCKER_USERNAME }}/nginx-copy:latest

    - name: Push to your Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-copy:latest
